### PR TITLE
Example-project improvements

### PR DESCRIPTION
**Pull request by peterdew**
Hi @timdwilson, 

I added a new featurebranche for the Example-project improvements we spoke about earlier at #19 . Please take a look. I changed the EF-approach to code-first, and database and seed-data is now created from code, so no seperate installation of test-database needed anymore. 
Please pull this to get feedback from you and contributors. It is an ongoing job, some more tasks need to be done, like updating the tutorial. 
I am not a contributor yet, you tried to make me one, didn't you? But I never received your invitation somehow. Please try again if possible. I would like to be one.

### CODE REVIEW

**Comment by timdwilson** [comment]
OK will do. I'll try again to add you as a contributor.

**Comment by timdwilson** [comment]
I also have a new get repository the needs to be updated with the new version after we test it out. I can give you access to that as well.

**Comment by peterdew** [comment]
I now see that I requested a pull from my feature branch to your master branch.
What I was intended to do, with this Pull request,  was to create the new feature branch in yóur repository too.  So others can work on it together with me, and finally merge it into the master in the future. Can you change it to that?

**Comment by timdwilson** [comment]
Hmmm I'll take look and see what I can do. Appreciate your work Peter!

**Comment by peterdew** [comment]
About my intension to 'create the new feature branch in yóur repository too', that seems not te be a common practice, so don't bother please. 
Additional changes in this area like modifying the tutorial to match the new example project can be the subject of another pull-request, I imagine. Is that correct?

**Comment by timdwilson** [comment]
Sounds good. Yes grouping features into one PR is best. Also I think what you are intending is to create a branch with another approach to feature or features in the app. You can certainly do that. That does not interfere with app at all and can be merged back in at some point.

**Comment by peterdew** [comment]
Oke, great. So a new branch in your repo called 'Example-project-codefirst' or something would make sense. I agree. Creating a branch in your repo is not permitted for me though as non-contributor, so please make me contributor for one time again. I changed my email-settings, there was something wrong with it! If that doesn't work, I will get in touch with GitHub Support.

**Comment by timdwilson** [comment]
Ok I added you. Maybe I didn't do it before? Let me know if that works...

**Comment by peterdew** [comment]
Hi Tim, That works! Thanks!

**Comment by peterdew** [comment]
Hi, this is a pull request to update the new feature branch 'Example-project-codefirst' Please review the changes for me. I wonder if the commit "Merge branch 'master' into ExampleProjectImprovements" should be in the pull request. It is the commit where I synced my fork after the recent updates to master from @groblerf

**Comment by timdwilson** [comment]
I'll take a look, Peter. Thanks!

**Pull request merged**
