### PR TITLE
Renamed events to new typeahead 0.11.1 api names and added new functionality.

### PR DESCRIPTION
**Pull request by groblerf**
Hallo Tim,

I like your idea for the MVC Model integration on the typeahead plugin, and have made some enhancements which you can add is you like.

The following was added or updated:
1. Added binding logic for additional events through data-api. The use can now alos bind their own select event without breaking existing functions.
2. Added identify function.
3. Changed defaults on typeahead to start searching remote after 3 characters to save postbacks and limit results returned. (This can maybe be set through the data-api as well?)
4. Added description of new methods in readme.md
5. Changed id on Autocomplete to a string to allow wider use of object ids, including guids, and string keys.
6. Fixed issue in HtmlHelpers that did not pass htmlAttributes along (line 48).
7. Added HtmlHelper methods to simplify the html attribute merging by using built-in functions (line 68-81)

Let me know what you think.

Kind Regards,
Francois Grobler

### CODE REVIEW

**Comment by timdwilson** [comment]
Hi Francois, sorry I missed your PR!  It looks like it has a conflict.  Would you mind resolving and I will merge it?

**Comment by peterdew** [comment]
Hi @groblerf and @timdwilson, 

This pull request did not change the example project. Is there a preferred way / standard procedure to update the example project along with each codechange? How did you manage that until now Tim? 

I am thinking of managing it through a nuget-package creation -> installation step. How exactly do you generate the nupkg-files Tim? 

What I have until now is this commandline-command: 
g:\tools\nuget.exe pack TypeaheadMvcModel.csproj; it creates a different package then the others.

**Comment by timdwilson** [comment]
Yes, NuGet does not update automatically which is a good thing actually. Have you tested that the new code works? There is a local tool you can download to manage creating a new version, including downloading the last version, I believe. I'll review and get back to you.

**Comment by peterdew** [comment]
@timdwilson. I was thinking about a local nuget package, nót to be updated to nuget.org. Imagine a nugetpackage called 'Twitter.Typeahead.MVC.Model.9.9.99.nupkg' that is automatically generated on each build of the typeaheadmvcmodel-project. Then it would be very easy to install the newest development-version. Just create an extra packet source in visual studio called TypeAhead localsource, and point to that nuget-dir. Then you can always uninstall and reinstall the most up to date development-version of the solution and start testing immediately. Teststeps would then be easy to reproduce. During creation of a new release there would be created a new version in the normal version-range of course, and only that should have been deployed to nuget.org. 
That's why I was interested in your procedure te generate nuget-packages. 
The goal of that tool you mention isn't very clear to me, but if you can find it, please let me know.

**Comment by peterdew** [comment]
@groblerf 
Hi Francois, I can't get your changes to be tested succesfully. The typeahead-field isn't working at all anymore. My teststeps were: 
1. Clone the example-code-first branch (your changes are merged into it)
1. Copy the files from Content and Script-directory over the dirs in the Example Project. 
1. Copy the content of the HtmlHelpers.cs.pp file into the Controllers/HtmlHelpers.cs file in the example project and fix the rootnamespace placeholder to the real namespace
1. Run the application and go to the /HelloWorld/Create page. 
1. Start typing a few characters in the name-field. 

Nothing happens, there is no autocomplete-functionality. Tried to debug this, but couldn't figure out why it is not working anymore. 
How did you test your changes? What were your teststeps to do it?

**Comment by groblerf** [comment]
Hallo Peter,

Have you had a look at the changes in the Readme file that explains the changes I made?

Kind Regards,
Francois Grobler
Director, IT Development & Professional Services
GESS (Pty) Ltd
Tel: 0861 GESS 00 (0861 4377 00)
Mobile: +27 (0) 82 577 9697

E-mail: groblerf@gess.co.za<mailto:groblerf@gess.co.za>

**Comment by peterdew** [comment]
Yes, I did. Didn't bring me a solution.
Did you test it in a similar way I did?

Op wo 20 sep. 2017 om 10:28 schreef Francois Grobler <
notifications@github.com>

**Comment by timdwilson** [comment]
Hi Peter,

I know what you're saying but I'd rather releases to NuGet be controlled by
hand rather than automated.  That prevents a bad release going out and
breaking everyone's code.  That said, my code base was more a launching pad
for others to use and adapt.  I suspect that many have already adapted the
code to suit their needs.  So, since it has been a long time since the last
update... for better or for worse... there is a high probability that their
code will break if they made extensive modifications.  Developers have
control over what NuGet updates to allow into their app so it's not a huge
issue.  They will know what they are doing when they update.

In any case, after the first "bump" when we release the first update as
devs need to modify their code, I hope that further updates will be
smooth.  Again, my desire to manually push out changes to NuGet is to give
devs peace of mind when they update... that the code has been thoroughly
tested and reviewed.  I hope that makes sense.

Tbh, I haven't reviewed all of your code changes so I hope that the package
still works lol.  If it doesn't work right now, we should roll back the
source to the last known working version...

I'm fairly busy at the moment.  When time allows, I will try to help out
more with testing and getting the code to work given everyone's
contributions.  There are also a fair amount of ideas that have come in in
the issues section... workarounds people have done etc.  It would be nice
to prioritize those and maybe allow an ability to upvote any as necessary.
The goal of course now is just getting the code to work with all of the
changes :)

Thanks for all of your work, Peter!  I and I'm sure many other devs really
appreciate it.

Tim

**Comment by groblerf** [comment]
Hi Peter,

My code changes are running in a production system as is.
I must admit that I have never looked at the example project, either when implementing or when developing.

I will have a look at the example project when I get a chance to see if I can see any issues.

Please note that one of the changes in my code-set is that the autocomplete will only trigger after the third character was typed. This makes your return domain smaller and more focused.

Kind Regards,
Francois Grobler
Director, IT Development & Professional Services
GESS (Pty) Ltd
Tel: 0861 GESS 00 (0861 4377 00)
Mobile: +27 (0) 82 577 9697

**Comment by peterdew** [comment]
Hi Francois @groblerf , 

Thanks for your response. I appreciate your work and commitment to share your enhancements! You're right, I overlooked that change about third character. I started testing with a longer teststring but I have the same results unfortunately. 
 
Exact the same problem do I have with my loading-spinner. I changed it for my real-life solution, and it worked like a charm. But afterwards I started testing it in the example-project, and there it doesn't. Must be something with the example-project. 

Looks like in one of another way the synchronous instead of the asynchronous typeahead-functionality is triggered, can that be?

**Comment by peterdew** [comment]
Hi Francois @groblerf. 

I updated the example-project in Master with the last changes, So you can review the problem easier. 
If you check out and test, you will get: Uncaught TypeError: this.source is not a function
source:autos should be source:autos.ttadapter() ??
If I change it to that, a get: GET     http://localhost:13617/HelloWorld/&       400 (Bad Request)
so something goes wrong creating the lookup request to the backend. 
Maybe you can shine your light on it once more :)

**Comment by groblerf** [comment]
Hallo Peter,

The ttAdapter was decommissioned by Bootstrap. The code I checked in was updated to use the new API available from the Twitter Typeahead component that the wrapper is using.

Maybe check your bootstrap version and the version of the bootstrap autocomplete?

I think we have a version clash here.

As of Bootstrap 3 the original typeahead was removed and switched to twitter’s typeahead as it had more features, was more stable and had less bugs.

Have a look at the following:
/*!
* typeahead.js 0.11.1
* https://github.com/twitter/typeahead.js
* Copyright 2013-2015 Twitter, Inc. and other contributors; Licensed MIT
*/

At the link above you can find the script downloads required:

  *   Download zipball of latest release<http://twitter.github.com/typeahead.js/releases/latest/typeahead.js.zip>.
  *   Download the latest dist files individually:
     *   bloodhound.js<http://twitter.github.com/typeahead.js/releases/latest/bloodhound.js> (standalone suggestion engine)
     *   typeahead.jquery.js<http://twitter.github.com/typeahead.js/releases/latest/typeahead.jquery.js> (standalone UI view)
     *   typeahead.bundle.js<http://twitter.github.com/typeahead.js/releases/latest/typeahead.bundle.js> (bloodhound.js + typeahead.jquery.js)
     *   typeahead.bundle.min.js<http://twitter.github.com/typeahead.js/releases/latest/typeahead.bundle.min.js>
Note: both bloodhound.js and typeahead.jquery.js have a dependency on jQuery<http://jquery.com/> 1.9+.
So to give you an idea, on my production system I’m using the following packages:
Bootstrap 3.3.6
Twitter.Typeahead v0.11.1
Twitter.Typeahead.MVC v1.1.2
Twitter.Typeahead.MVC.Model v1.0.7

Kind Regards,
Francois Grobler
Director, IT Development & Professional Services
GESS (Pty) Ltd
Tel: 0861 GESS 00 (0861 4377 00)
Mobile: +27 (0) 82 577 9697

E-mail: groblerf@gess.co.za<mailto:groblerf@gess.co.za>

**Comment by peterdew** [comment]
Good point. Updated Bootstrap to the latest version. Didn't get it working yet. What did you mean with 'and the version of the bootstrap autocomplete'?

**Comment by timdwilson** [comment]
Thanks Francoise and Peter for your dialog and work on the codebase!  I
hope to take a look at any pressing issues this weekend and want to try and
get a new version of the NuGet package out in the next week or two.

**Comment by peterdew** [comment]
Hi @timdwilson , 
Could you make some time for this yet? Problem is that it is not easily testable for me. I am not going to install and host sql-server on my developermachine. As soon as things doesn't work I can't determine if it is the test-setup or the new commits that broke the library. 

If I have time I will set up a [local feed](https://docs.microsoft.com/nl-nl/nuget/hosting-packages/local-feeds) for nuget-packages on  my machine and build [alpha-versions](https://docs.microsoft.com/nl-nl/nuget/create-packages/prerelease-packages) of the nuget-packages to my local feed from several points in history to make a clean and complete test to a small example solution. 

@groblerf Thanks for clarifying the dependancy's for your updated code. I think we should change the dependancy-settings in the .nuspec-file for it. (Wich by the way isn't part of the solution but is in your possession @timdwilson ?)

**Comment by timdwilson** [comment]
Sorry Peter I’ve been really busy. I’ll make some time this weekend.

**Pull request merged**
